name: 'Version composite action'
description: 'A composite action to handle versioning'
inputs:
  token:
    required: false
    description: 'A token to access private github repos'
    
outputs: 
  new-tag:
    description: "The new tag"
    value: ${{ steps.semantic.outputs.new_tag }}
  new-version:
    description: "The new version"
    value: ${{ steps.semantic.outputs.new_version }}
  changelog:
    description: "Changelog"
    value: ${{ steps.semantic.outputs.changelog }}
  previous-tag:
    description: "The previous annotated tag"
    value: ${{ steps.semantic.outputs.previous_tag }}
  prerelease:
    description: "Prerelease"
    value: ${{ steps.semantic.outputs.prerelease }}
  previous-light-tag:
    description: "The previous lightweight tag"
    value: ${{ steps.semantic.outputs.previous_light_tag }}
  branch:                                                             # DEPRECATED
    description: "Branch"
    value: ${{ steps.extract_branch.outputs.branch }}
  new-numbered:
    description: "New tag without branch name and commit number"
    value: ${{ steps.semantic.outputs.new_numbered }}
    
runs:
    using: "composite"
    steps:
      - name: Checkout
        # if: startsWith(github.event.head_commit.message, '(build):') || startsWith(github.event.commits[0].message, '(build):') || endsWith(github.event.head_commit.message, '--build') || endsWith(github.event.commits[0].message, '--build')
        uses: actions/checkout@v2
        with:
          fetch-depth: 0                # fetch the whole repo history
          persist-credentials: false
          
      # - name: Extract branch name                   # DEPRECATED
      #   id: extract_branch
      #   shell: bash
      #   run: echo "##branch;$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: Handle version update
        uses: teveltech/github-tag-action@set-output
        id: semantic
        with:
          dry_run: true
#           github_token: ${{ inputs.token }}
