name: 'Version composite action'
description: 'A composite action to handle versioning'
inputs:
  token:
    required: false
    description: 'A token to access private github repos'
outputs: 
  new_tag:
    description: "The new tag"
    value: ${{ steps.semantic.outputs.new_tag }}
  new_version:
    description: "The new version"
    value: ${{ steps.semantic.outputs.new_version }}
  changelog:
    description: "Changelog"
    value: ${{ steps.semantic.outputs.changelog }}
  previous_tag:
    description: "The previous annotated tag"
    value: ${{ steps.semantic.outputs.previous_tag }}
  prerelease:
    description: "Prerelease"
    value: ${{ steps.semantic.outputs.prerelease }}
  previous_light_tag:
    description: "The previous lightweight tag"
    value: ${{ steps.semantic.outputs.previous_light_tag }}
  branch:
    description: "Branch"
    value: ${{ steps.extract_branch.outputs.branch }}
runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0                # fetch the whole repo history
          persist-credentials: false
          
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Handle version update
        uses: teveltech/github-tag-action@annotated-tag
        id: semantic
        with:
          github_token: ${{ inputs.token }}
          dry_run: true
